### PR TITLE
Let one source use another source's classifier

### PR DESCRIPTION
**Pull request by StephenChan**
For issue #537. So far this PR just implements the source state logic, without adding/revising classifier usage semantics yet (that is why this PR's still WIP).

The work so far includes changes to new/edit source forms, handling cases like classifier deletion and labelset editing, and unit tests thereof.

Also revised the source main page layout, mainly to try and group all the classifier related info together; might have more ideas for improvement later, but this should do for now.

Screenshots follow; first, the new/edit source form's option for the classifier mode:

source-form_train

source-form_use-existing

One possible error when submitting this form; there are also errors for not having permission to the classifier's source, or for the classifier not existing:

error_labelset-mismatch

Updated layout to the source main page:

source-main

Three possible classifier status displays; don't mind the "minimum of 3", that's just the setting I use for testing:

status_train

status_train-none

status_use-existing

And two more. The first is when you had a classifier selected, but then it got deleted (say, because the classifier's source changed its labelset or feature extractor). The second is how it looks when you leave the classifier ID field blank; this would essentially turn off automatic classification, in case that's ever desired (and for technical reasons, I think it's also a useful default state to have).

status_deleted

status_none

And when you try to edit your labelset when using another source's classifier, it just doesn't let you. Maybe this can be made more lenient later (like allowing the labelset to be a superset, instead of saying it must be identical), but opting to keep it strict, safe and simple for a start.

labelset-edit-denied

Meanwhile, made a couple steps towards issue #306 (making date displays consistent); lib.utils date_display() and datetime_display() both go for the server's local time. But in the future we may want to detect the user's timezone or let them set it.

### CODE REVIEW

**Comment by Jordan-Pierce** [comment]
@StephenChan 

Just lurking, but thoughts for the following:

"And when you try to edit your labelset when using another source's classifier, it just doesn't let you. Maybe this can be made more lenient later (like allowing the labelset to be a superset, instead of saying it must be identical), but opting to keep it strict, safe and simple for a start."

What about having an editable mapping between the labelset of the Classifier's Source and the users' Source labelset? So if my Source has "Acropora" in it, but the classifier I want to use has "Acropora Sp." (or something equally as trivial), instead of adopting the classifier's labelset, before submitting a request to classify I can choose how I would want to map each the classifier's output labels to the labels in my Source's labelset? This would be useful for these situations (where the naming convention is just slightly different), but also for more extreme cases as well, depending on the user's needs.

Just a thought. Looking forward to the new feature!

**Comment by StephenChan** [comment]
Hmm yeah, maybe. We try to discourage duplicate labels on CoralNet, but the reality is that some of them have stuck around in prominent sources. (Doesn't help that we never got around to issue #415, but still.) Also, an editable mapping could have a few possible uses, including letting you map two or more labels of the classifier's source to a single label of your source.

**Comment by Jordan-Pierce** [comment]
> Hmm yeah, maybe. We try to discourage duplicate labels on CoralNet, but the reality is that some of them have stuck around in prominent sources. (Doesn't help that we never got around to issue #415, but still.) Also, an editable mapping could have a few possible uses, including letting you map two or more labels of the classifier's source to a single label of your source.

Agreed, the latter would also allow a user to use multiple classifiers (if the functionality is provided), and then map their each of their labels to a common label that they desire.

**Comment by StephenChan** [comment]
- Updated the backend logic (feature extraction, training, classification) to support the new classifier options.

- Changed the `deployed_classifier` field semantics so that it's always the classifier being used for classifying that source's images. So, now it's auto-populated whenever the `trains_own_classifiers` mode is True. I thought this scheme seemed a little simpler compared to only looking at `deployed_classifier` when the train mode is False. With this change, we can check `deployed_classifier` to see what is being used for classification, without caring about whether we're in train mode or not.

- Revised the wording of help texts to better suggest that you can use the `deployed_classifier` field to choose a previously trained classifier in your own source. This capability didn't require any special code. And I didn't see a reason to delete the trained classifiers when toggling train mode off or on, so that's not an obstacle.

- Updated the descriptive text of the currently deployed classifier, including saying the train date, and saying whether it's the latest classifier of its source (and if not, saying what the latest classifier is).

source-edit

source-main

In this PR overall, I kept making revisions and adding tests here and there as I thought of them. So it's likely that the code can be better organized and that I overlooked some situations. But I don't know if I can improve it by staring at the code more right now, so I'll just keep an eye on things after updating the server. I'll also think about how the displayed info in various cases can be improved.

That's it for this PR; will have to think about the label mapping idea more, to see if it's the best way to meet the relevant needs, and to consider what the UI might look like.

**Comment by StephenChan** [comment]
> Does this new feature currently allow for users to train on top of the existing classifier that they choose? Or does the source at this point serve as a place for users to upload images (and point locations), for which an existing classifier will label?

Just the second one.

> What happens after a user adds additional labels to the source that would normally trigger a (re)training?

Nothing in particular. However, if you later decided to switch back to the 'Train' classifier mode, then a (re)training would happen.

And good to hear!

**Pull request merged**
